source 'https://rubygems.org'

gem 'ruby-openai'
gem 'csv'
gem 'sqlite3'
gem 'json'
gem 'byebug'
gem 'sinatra'
gem 'rackup'
gem 'rack-cors'
require 'webrick'
require 'webrick/https'
require 'openssl'
